export const compliments: string[] = [
  "Amazing!",
  "Awesome!",
  "Beautiful!",
  "Bravo!",
  "Brilliant!",
  "Clever!",
  "Cool!",
  "Excellent!",
  "Fabulous!",
  "Fantastic!",
  "Good Job!",
  "Great Job!",
  "Impressive!",
  "Incredible!",
  "Magnificent!",
  "Nice!",
  "Outstanding!",
  "Perfect!",
  "Smart!",
  "Terrific!",
  "Wonderful!",
];
